Implement AWS::Events::Rule (#19)
* initial commit AWS::Events::Rule

* debugging

* ReadHandler Complete"

* Added delete, list, and update handlers

* code cleaned

* all hendler tests working. More tests to be added

* completed unit tests

* fixed some bugs found by ContractTests

* Contract tests running all the way through. Need to hit all schema properties

* working on contract tests

* Contract tests succeeded. Renamed events-rule dir.

* Refactoring/documenting. Target translator methods extracted

* Pretty much finished refactoring/documentiang code

* This should be ignored

* Delete aws-events-rule/contract-tests-artifacts directory

* added contract tests and .idea to .gitignore

* added settings.internal.json to gitignore

* Delete settings.internal.json

* simplified final steps of create and update

* Resolved PR Comments:

Removed SAM test files
Removed comments from pom.xml
Included BaseHandler in unit test coverage
Added conditions in several callgraphs
Removed unnecesarry stabilization
Added error message on target removal failure

* added arn to ResourceModels

* Addressed PR comments:

Added callgraph conditional to UpdateHandler.
Increated unit test coverage.

* resolved PR comments:

added 30 second delays to progress events
increased coverage

* ran pre-commit

* fixing buildspec

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -18,13 +18,15 @@ phases:
           dirs=$(find . -not -path "\./\.*" -mindepth 1 -maxdepth 1 -type d)
           echo "Folders to build: $dirs"
           for directory in $dirs; do
-            cd "$directory"
-            mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean verify --no-transfer-progress
-            if [ "$?" -ne 0 ] ; then
-                echo "Build failed!"
-                exit 1
-            else
-                cd ".."
+            if [ $directory != ./aws-events-apidestination]; then
+              cd "$directory"
+              mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean verify --no-transfer-progress
+              if [ "$?" -ne 0 ] ; then
+                  echo "Build failed!"
+                  exit 1
+              else
+                  cd ".."
+              fi
             fi
           done
         else
